{
 "title": "Tracer-APP-Dashboard",
 "tags": [
  "tracing",
  "io-operations",
  "tempo"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Service Traces",
   "type": "stat",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "filters": [
      { "id": "b538f6df", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Recent IO Tasks Traces",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ resource.service.name=\"tracer-app\" && name=\"io-tasks-handler\" }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "File Operations Timeline",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ resource.service.name=\"tracer-app\" && (name=\"write-file\" || name=\"read-file\" || name=\"delete-file\") }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Error Traces",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{ resource.service.name=\"tracer-app\" && status=error }",
     "tableType": "traces"
    }
   ]
  }
 ]
}